name: Comprehensive Collision Prevention & Quality Gates

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  module-boundaries:
    name: Module Boundary Enforcement
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint module boundary checks
        run: pnpm nx run-many -t lint --parallel --maxParallel=4

      - name: Validate token namespace compliance
        run: |
          echo "🔍 Checking CSS token namespace compliance..."
          # Ensure all CSS tokens use --ds-* prefix
          if grep -r "^[[:space:]]*--[^d][^s]-" packages/design-tokens/libs/tokens/css/ 2>/dev/null; then
            echo "❌ Found CSS tokens without ds- prefix"
            exit 1
          fi
          echo "✅ All CSS tokens use --ds-* prefix"

          echo "🔍 Checking JavaScript token namespace compliance..."
          # Ensure all JS tokens use ds prefix (exclude comments and strings)
          if grep -r "^[[:space:]]*export.*[^d][^s][A-Z]" packages/design-tokens/libs/tokens/js/ 2>/dev/null; then
            echo "❌ Found JS tokens without ds prefix"
            exit 1
          fi
          echo "✅ All JS tokens use ds prefix"

      - name: Validate import path compliance
        run: |
          echo "🔍 Checking for deprecated dist/ import paths..."
          # Ensure no imports use deprecated dist/ paths
          if grep -r "from.*design-tokens.*dist/" apps/ packages/ 2>/dev/null; then
            echo "❌ Found deprecated dist/ import paths"
            echo "Please update to use libs/tokens/ paths instead"
            exit 1
          fi
          if grep -r "import.*design-tokens.*dist/" apps/ packages/ 2>/dev/null; then
            echo "❌ Found deprecated dist/ import paths"
            echo "Please update to use libs/tokens/ paths instead"
            exit 1
          fi
          echo "✅ No deprecated dist/ import paths found"

      - name: Check collision-safe token outputs
        run: |
          echo "🔍 Verifying collision-safe token outputs exist..."
          
          # Check platform-rooted directories exist
          for platform in css scss js ts json dart compose react-native; do
            if [ ! -d "packages/design-tokens/libs/tokens/$platform" ]; then
              echo "❌ Missing platform directory: libs/tokens/$platform"
              exit 1
            fi
          done
          echo "✅ All platform-rooted directories exist"

          # Verify ds- prefixed outputs
          if [ -f "packages/design-tokens/libs/tokens/css/tokens.css" ]; then
            if ! grep -q "^--ds-" packages/design-tokens/libs/tokens/css/tokens.css; then
              echo "❌ CSS tokens don't use --ds- prefix"
              exit 1
            fi
          fi
          echo "✅ Token outputs are collision-safe"

  token-pipeline:
    name: Token Pipeline Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build design tokens
        run: pnpm nx run design-tokens:tokens:build

      - name: Validate token schema compliance
        run: |
          echo "🔍 Validating token schema compliance..."
          
          # Check for token schema violations
          cd packages/design-tokens
          
          # Validate JSON schema
          if [ -f "libs/tokens/json/tokens.json" ]; then
            # Basic JSON validation
            node -e "JSON.parse(require('fs').readFileSync('libs/tokens/json/tokens.json', 'utf8'))"
            echo "✅ JSON tokens are valid"
          fi
          
          # Check for required token categories
          required_categories=("color" "typography" "spacing" "shadow")
          for category in "${required_categories[@]}"; do
            if ! grep -q "\"$category\"" libs/tokens/json/tokens.json 2>/dev/null; then
              echo "⚠️  Warning: $category tokens not found"
            fi
          done

      - name: Test token collision detection
        run: |
          echo "🔍 Testing runtime collision detection..."
          cd packages/shared-utils
          
          # Run collision detection tests
          pnpm test --testNamePattern="runtime.*guard" --passWithNoTests

      - name: Validate cross-platform consistency
        run: |
          echo "🔍 Validating cross-platform token consistency..."
          
          # Compare token counts across platforms
          css_count=$(grep -c "^--ds-" packages/design-tokens/libs/tokens/css/tokens.css 2>/dev/null || echo "0")
          js_count=$(grep -c "^export.*ds" packages/design-tokens/libs/tokens/js/tokens.js 2>/dev/null || echo "0")
          
          echo "CSS tokens: $css_count"
          echo "JS tokens: $js_count"
          
          # Allow for some variation due to platform-specific tokens
          if [ "$css_count" -gt 0 ] && [ "$js_count" -gt 0 ]; then
            echo "✅ Tokens generated for multiple platforms"
          else
            echo "⚠️  Warning: Low token count detected"
          fi

  storybook-composition:
    name: Storybook Composition Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build design tokens
        run: pnpm nx run design-tokens:tokens:build

      - name: Test Storybook web build
        run: |
          echo "🔍 Testing Storybook web build..."
          cd packages/design-system
          timeout 120 pnpm build-storybook || echo "Storybook build completed or timed out"

      - name: Validate Storybook composition configs
        run: |
          echo "🔍 Validating Storybook composition configurations..."
          
          # Check for required Storybook configs
          configs=("main.ts" "main.mobile.ts" "main.desktop.ts")
          for config in "${configs[@]}"; do
            if [ ! -f "packages/design-system/.storybook/$config" ]; then
              echo "❌ Missing Storybook config: $config"
              exit 1
            fi
          done
          echo "✅ All Storybook composition configs present"

          # Check for isolated Vite configs
          vite_configs=("vite.config.storybook.ts" "vite.config.mobile.ts" "vite.config.desktop.ts")
          for config in "${vite_configs[@]}"; do
            if [ ! -f "packages/design-system/.storybook/$config" ]; then
              echo "❌ Missing Vite config: $config"
              exit 1
            fi
          done
          echo "✅ All Vite isolation configs present"

  security-scan:
    name: Security & Dependency Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Check for sensitive data leaks
        run: |
          echo "🔍 Checking for sensitive data in token files..."
          
          # Check for API keys, secrets, or personal info in tokens
          if grep -r -i "api[_-]key\|secret\|password\|token.*[0-9a-f]\{20,\}" packages/design-tokens/libs/tokens/ 2>/dev/null; then
            echo "❌ Potential sensitive data found in tokens"
            exit 1
          fi
          echo "✅ No sensitive data detected in tokens"

      - name: Validate token file permissions
        run: |
          echo "🔍 Checking token file permissions..."
          
          # Ensure token files are not executable
          if find packages/design-tokens/libs/tokens/ -type f -executable 2>/dev/null | grep -q .; then
            echo "❌ Found executable token files"
            exit 1
          fi
          echo "✅ Token file permissions are secure"

  performance-budget:
    name: Performance Budget Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build design tokens
        run: pnpm nx run design-tokens:tokens:build

      - name: Check token bundle sizes
        run: |
          echo "🔍 Checking token bundle sizes..."
          
          # Define size limits (in bytes)
          CSS_LIMIT=51200    # 50KB
          JS_LIMIT=25600     # 25KB
          JSON_LIMIT=102400  # 100KB
          
          # Check CSS bundle size
          if [ -f "packages/design-tokens/libs/tokens/css/tokens.css" ]; then
            css_size=$(wc -c < packages/design-tokens/libs/tokens/css/tokens.css)
            echo "CSS bundle size: ${css_size} bytes (limit: ${CSS_LIMIT})"
            if [ "$css_size" -gt "$CSS_LIMIT" ]; then
              echo "❌ CSS bundle exceeds size limit"
              exit 1
            fi
          fi
          
          # Check JS bundle size
          if [ -f "packages/design-tokens/libs/tokens/js/tokens.js" ]; then
            js_size=$(wc -c < packages/design-tokens/libs/tokens/js/tokens.js)
            echo "JS bundle size: ${js_size} bytes (limit: ${JS_LIMIT})"
            if [ "$js_size" -gt "$JS_LIMIT" ]; then
              echo "❌ JS bundle exceeds size limit"
              exit 1
            fi
          fi
          
          # Check JSON bundle size  
          if [ -f "packages/design-tokens/libs/tokens/json/tokens.json" ]; then
            json_size=$(wc -c < packages/design-tokens/libs/tokens/json/tokens.json)
            echo "JSON bundle size: ${json_size} bytes (limit: ${JSON_LIMIT})"
            if [ "$json_size" -gt "$JSON_LIMIT" ]; then
              echo "❌ JSON bundle exceeds size limit"
              exit 1
            fi
          fi
          
          echo "✅ All bundles within size limits"

  report-status:
    name: Report Overall Status
    runs-on: ubuntu-latest
    needs: [module-boundaries, token-pipeline, storybook-composition, security-scan, performance-budget]
    if: always()
    
    steps:
      - name: Report Success
        if: needs.module-boundaries.result == 'success' && needs.token-pipeline.result == 'success' && needs.storybook-composition.result == 'success' && needs.security-scan.result == 'success' && needs.performance-budget.result == 'success'
        run: |
          echo "✅ ALL COLLISION PREVENTION & QUALITY GATES: PASSED"
          echo ""
          echo "🛡️  Module boundary enforcement: ✅ PASSED"
          echo "🔧 Token pipeline validation: ✅ PASSED"  
          echo "📚 Storybook composition: ✅ PASSED"
          echo "🔒 Security & dependency audit: ✅ PASSED"
          echo "⚡ Performance budget validation: ✅ PASSED"
          echo ""
          echo "🎉 Ready for deployment!"

      - name: Report Failure
        if: needs.module-boundaries.result == 'failure' || needs.token-pipeline.result == 'failure' || needs.storybook-composition.result == 'failure' || needs.security-scan.result == 'failure' || needs.performance-budget.result == 'failure'
        run: |
          echo "❌ COLLISION PREVENTION & QUALITY GATES: FAILED"
          echo ""
          echo "🛡️  Module boundary enforcement: ${{ needs.module-boundaries.result }}"
          echo "🔧 Token pipeline validation: ${{ needs.token-pipeline.result }}"
          echo "📚 Storybook composition: ${{ needs.storybook-composition.result }}"
          echo "🔒 Security & dependency audit: ${{ needs.security-scan.result }}"
          echo "⚡ Performance budget validation: ${{ needs.performance-budget.result }}"
          echo ""
          echo "Please check the logs above for specific violations"
          exit 1
