name: Visual Regression Tests

on:
  pull_request:
    paths:
      - packages/design-system/**
      - packages/design-tokens/**
      - .storybook/**

jobs:
  loki-visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true

      - name: Restore Nx cache
        uses: actions/cache@v4
        with:
          path: tmp/nx-cache
          key: ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml', 'nx.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Export Nx Cloud token
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          NX_TOKEN="$(gh variable get NX_CLOUD_ACCESS_TOKEN -R \"$GITHUB_REPOSITORY\" --json value --jq '.value' 2>/dev/null || true)"
          if [ -n "$NX_TOKEN" ]; then
            echo "NX_CLOUD_ACCESS_TOKEN=$NX_TOKEN" >> "$GITHUB_ENV"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.20.0
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start Nx self-healing run
        run: |
          if [ -n "$NX_CLOUD_ACCESS_TOKEN" ]; then
            pnpm exec nx start-ci-run --no-distribution --fix-tasks="*lint*,*format*"
          else
            echo "Skipping Nx self-healing bootstrap (NX_CLOUD_ACCESS_TOKEN not set)"
          fi

      - name: Build design tokens
        run: pnpm nx run design-tokens:build

      - name: Build Storybook
        run: pnpm nx run design-system:build-storybook

      - name: Download reference images
        run: |
          git lfs fetch
          git lfs checkout

      - name: Run Loki visual tests
        run: |
          npx concurrently -k -s first -n "SB,LOKI" -c "magenta,blue" \
            "npx http-server packages/design-system/storybook-static --port 6006 --silent" \
            "npx wait-on http://127.0.0.1:6006 && pnpm nx run design-system:loki:test"

      - name: Upload visual diffs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: loki-diffs
          path: packages/design-system/.loki/current/

      - name: Update references on main
        if: github.ref == 'refs/heads/main' && success()
        run: |
          pnpm nx run design-system:loki:update
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/design-system/.loki/reference/
          git commit -m "Update Loki reference images" || exit 0
          git push

      - name: Apply Nx self-healing fixes
        if: always()
        run: |
          if [ -n "$NX_CLOUD_ACCESS_TOKEN" ]; then
            pnpm exec nx fix-ci
          else
            echo "Skipping Nx self-healing fix (NX_CLOUD_ACCESS_TOKEN not set)"
          fi
